endorse account in bot-community.py
encointer/encointer-node pull request #122
Opened 2021-10-13 05:56 UTC by anizeani

rust code obviously not^^

2021-10-13 06:03 UTC, clangenb commented on client/src/main.rs
> +                    .account_arg()
account will be the sender of the extrinsic. you need to an additional argument, which will be the endorsee account

2021-10-13 06:03 UTC, clangenb commented on client/src/main.rs
> +                        return Ok(())
you don't need this part.

2021-10-13 06:03 UTC, clangenb commented on client/src/main.rs
> +                        "register_participant",
this should be endorse_newcomer

2021-10-13 06:10 UTC, clangenb commented on client/src/main.rs
> +                        proof
this should be the endorsee then

2021-11-14 13:58 UTC, brenzi commented
is this ready? please mark PR ready and request my review

2021-11-15 07:44 UTC, anizeani commented
Endorsements implemented in run method. 
Endorsments work, but in await_block error is thrown: 
ExtrinsicFailed: Module { index: 9, error: 0, message: None } DispatchInfo { weight: 10000, class: DispatchClass::Normal, pays_fee: Pays::Yes }

2021-11-15 07:55 UTC, anizeani commented
> Endorsements implemented in run method. Endorsments work, but in await_block error is thrown: ExtrinsicFailed: Module { index: 9, error: 0, message: None } DispatchInfo { weight: 10000, class: DispatchClass::Normal, pays_fee: Pays::Yes }

I think this happens, if accounts are registered and not purged, and then registered again. --> run chain again with --tmp argument

2021-11-15 10:55 UTC, brenzi commented
ok, I'll try to reproduce. can you please resolve the conversations above if you consider them addressed?

2021-11-15 11:27 UTC, brenzi commented
1. I don't like your approach of creating, funding and endorsing accounts one-by-one. This takes way too long and is rather ugly compared to how the the rest of the script works. please do it the same way newbies are created (actually, I suggest to just increase the number of newbies to create by the number of endorsees in the current round and then you just need to specifically endorse the first N newbies with a single function call and the list of endorsees as argument. Less LOC and I'm pretty sure this will solve your issue mentioned above which probably is a race condition.
2. You continue endorsing accounts without taking note of how many endorsements are left. This leads to many failed extrinsics once the budget is exhausted. not nice for debugging
3.

2021-11-15 11:30 UTC, brenzi requested changes
see comment above

2021-11-15 13:05 UTC, anizeani commented
1. I implemented the methodology the way you suggested. 
2. I didn't understand where we can find out the contingent of available endorsees... So how do I find out how many are aloud?

2021-11-19 09:16 UTC, clangenb requested changes
Why do you resolve all my comments without fixing? You clearly have not touched the issues I mentioned

2021-11-20 14:29 UTC, brenzi commented
@anizeani: The number of endorsees allowed is a runtime constant. You could fetch it through rpc, but I think it's fine to just define a constant in the py script. I believe we initialized the total number of endorsees per bootstrapper to 50

2021-11-25 10:02 UTC, clangenb commented on client/src/main.rs
> +	api.get_storage_double_map(
Your code should not compile, because you don't pass matches here.

2021-12-04 19:57 UTC, brenzi commented
what is the status here?

2021-12-05 11:06 UTC, clangenb commented
When testing, there were nonce errors, which makes sense as multiple accounts are endorsed withing the same block, but we were using the online `compose_extrinsic`. However, we want to be able to endorse multiple endorsees at once to speed up the process. This means we need to manually increment the nonce either on python  or rust side. Regardless of the approach, the rust code needs to be touched, which means it hangs on me.

2021-12-05 17:36 UTC, brenzi commented
I suggest to do it like the cli `faucet` command in rust: count up nonces in the rust CLI. pretty much copy-paste

2021-12-06 17:47 UTC, clangenb commented
I decided to see this through to the end because it expected some ping-pong between rust and python adjustments (which did indeed happen).

* Loosely tested endorsements, seems to work.
* I was wondering about the statically assigned value of performing two endorsements per ceremony. This seems really low to me. Is this something you discussed @brenzi, @anizeani?

2021-12-07 08:58 UTC, anizeani commented
If I'm not mistaken, then 2 endorsees is what we decided, but since this parameter is parametrizable, we can for stress test just augment it, right?

2021-12-07 14:17 UTC, clangenb approved these changes
I tested some more, added 101 endorsees, 2 newbies, could register them all successfully, for the first (bootstraping) ceremony. Which leads to the expected meetup distribution:

```
number of known accounts: 113
meetups assigned for 113 participants with sizes: [12, 12, 12, 11, 11, 11, 11, 11, 11, 11]
```

2021-12-07 14:17 UTC, clangenb commented
@brenzi ready to merge IMO.

2021-12-08 13:23 UTC, clangenb commented on client/bot-community.py
> +NUMBER_OF_ENDORSEMENTS_PER_REGISTRATION = 101
I reckon we will fine tune this afterwards. The script does not support meetups anyhow until we integrated handling of randomized meetups.

2021-12-08 14:07 UTC, brenzi approved these changes

2021-12-08 14:12 UTC, merged